project_name: rs485-controller

release:
  github:
    owner: TheCacophonyProject
    name: rs485-controller
  name_template: '{{.Tag}}'

builds:
- binary: rs485-controller
  main: ./cmd/rs485-controller
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
- binary: trap-cli
  main: ./cmd/trap-cli
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
- binary: trap-sequence
  main: ./cmd/trap-sequence
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}


nfpm:
  vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Controller for devices connect by RS485 for the Cacophony Project
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/cacophonator-rs485-controller.service": "/etc/systemd/system/cacophonator-rs485-controller.service"
    "_release/org.cacophony.rs485controller.conf": "/etc/dbus-1/system.d/org.cacophony.rs485controller.conf"
  config_files:
    "_release/rs485-controller.yaml": "/etc/cacophony/rs485-controller.yaml"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
